### ISSUE TITLE
Category with permissions.

### ISSUE THREAD

**Issue by Grellim** [JEFF-Media-GbR/Spigot-Drop2Inventory#34]
Create a config for editable category like categories.yml. Where can be created custom category with items that we want, like:

```
Categories:
  Monsters: *The custom category
    permission: drop2inv.use.monsters *The permission to pickup that items
    nopermissions-drop: false *If 'false' don't has the permission, the item will be dropped
    items: *items that will be pickup.
      - rotten_flesh
      - spider_eye
      - gunpowder
```
